const PRINT_TYPES = {
  ORDER_SINGLE: 'ORDER_SINGLE',
  ORDER_TOTAL: 'ORDER_TOTAL',
  IMPORT_ORDER: 'IMPORT_ORDER',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT'
};

const PRINT_TITLES = {
  ORDER_SINGLE: 'PHIẾU GIAO NHẬN VÀ THANH TOÁN',
  ORDER_TOTAL: 'PHIẾU GỘP ĐƠN TỔNG',
  IMPORT_ORDER: 'PHIẾU NHẬP KHO',
  PAYMENT_RECEIPT: 'PHIẾU THU TIỀN'
};

module.exports = { PRINT_TYPES, PRINT_TITLES };
