/* GENERATED FILE — edit templates/printTemplates.source/part-01.jsfrag, templates/printTemplates.source/part-02.jsfrag, templates/printTemplates.source/part-03.jsfrag and run npm run build:source-bundles. */
const t=require("./print/dmsExactSalesInvoice.template"),{getCompanyProfile:n}=require("../src/config/company-profile.config");function e(t){
return String(t??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}function o(t,n){
return t.formatMoney?t.formatMoney(n):Number(n||0).toLocaleString("vi-VN")}function s(t,n){return""===n||null==n?"":o(t,n)}function i(t,n=""){return e(t||n)}function r(t){
return t.erpInvoiceV46||{}}function a(t){const n=r(t).header||{};return{invoiceCode:n.invoiceCode||t.document?.invoiceCode||t.document?.code||"",
orderCode:n.orderCode||t.document?.customerOrderCode||t.document?.code||"",orderDateTime:n.orderDateTime||t.document?.dateTime||t.document?.date||"",
invoiceType:n.invoiceType||t.document?.type||"Từ NVTT",paymentTerm:n.paymentTerm||t.document?.terms||"đáo hạn trong 7 ngày",truckNo:n.truckNo||t.document?.vehicleNo||"",
taxCode:n.taxCode||t.customer?.taxCode||""}}function d(t){const e=r(t).distributor||{},o=n();return{code:e.code||t.company?.code||o.code,name:e.name||t.company?.name||o.name,
phone:e.phone||t.company?.phone||o.phone,address:e.address||t.company?.address||o.address}}function c(t){const n=r(t).customer||{};return{
customerCode:n.customerCode||t.customer?.code||"",customerName:n.customerName||t.customer?.name||"",phone:n.phone||t.customer?.phone||"",
deliveryAddress:n.deliveryAddress||t.customer?.address||"",taxCode:n.taxCode||t.customer?.taxCode||""}}function l(t){const n=r(t).salesStaff||{};return{
staffCode:n.staffCode||t.staff?.code||"",staffName:n.staffName||t.staff?.name||"",phone:n.phone||t.staff?.phone||""}}function m(t){const n=r(t)
;return Array.isArray(n.items)&&n.items.length?n.items:(t.items||[]).map(t=>({...t,lineNo:t.lineNo||t.stt,productCode:t.productCode||t.code,productName:t.productName||t.name,
quantityCsSu:t.quantityCsSu||t.caseDisplay,quantity:t.quantity??t.qty,
priceBeforeTaxBeforePromotion:t.priceBeforeTaxBeforePromotion??t.listPriceBeforeVat??t.priceBeforeVat??t.price,
priceAfterTaxBeforePromotion:t.priceAfterTaxBeforePromotion??t.listPriceAfterVat??t.priceAfterVatBeforeDiscount,
priceAfterTaxAfterPromotion:t.priceAfterTaxAfterPromotion??t.priceAfterVatAfterDiscount??t.priceAfterDiscount,vatAmount:t.vatAmount??t.tax,lineAmount:t.lineAmount??t.amount,
isPromotionGift:t.isPromotionGift??t.isPromo,promotionRows:t.promotionRows||[],appliedPromotions:t.appliedPromotions||[],promotions:t.promotions||[],
productSnapshot:t.productSnapshot||{},product:t.product||{}}))}function h(t){return Array.isArray(t)?t:[]}function u(t){
return[...h(t?.promotionRows),...h(t?.appliedPromotions),...h(t?.promotions),...h(t?.productSnapshot?.promotions),...h(t?.product?.promotions)]}function p(t,n={}){
const e=t?.promotionCode||t?.code||t?.programCode||t?.ctkmCode||"",o=n.productCode||n.code||t?.productCode||"",s=n.productName||n.name||t?.productName||"",i=n.priceBeforeTaxBeforePromotion??n.beforeTaxAmount??n.amountBeforeTax??n.lineAmount??n.amount??0
;return{...t,promotionCode:e,code:e,description:t?.description||t?.promotionDescription||t?.programDescription||t?.promotionName||t?.name||t?.title||"",
qualifiedAmount:t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??t?.purchaseAmountBeforeTax??t?.purchaseAmount??t?.goodsAmountBeforeTax??t?.goodsAmount??i,
discountPercent:t?.discountPercent??t?.percent??t?.rate??t?.discountRate,discountBeforeTax:t?.discountBeforeTax??t?.beforeTax??t?.ckBeforeTax??t?.discountAmountBeforeTax,
discountAfterTax:t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax,promotionType:t?.promotionType||t?.type||t?.scope||t?.level||t?.discountType,
productCode:o,productName:s,lineType:n.isPromotionGift?"PROMO":t?.lineType||n.lineType||"SALE"}}function g(t){
return[T(t),t?.productCode||"",Number(t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax??0)||0,Number(t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??0)||0].join("|")
}function v(t){const n=r(t),e=[];for(const t of h(n.promotions))e.push(p(t));for(const n of h(t.promotions))e.push(p(n));for(const n of m(t))for(const t of u(n))e.push(p(t,n))
;const o=new Set;return e.filter(t=>{if(!T(t))return!1;const n=g(t);return!o.has(n)&&(o.add(n),!0)})}function y(t){const n=r(t)
;return Array.isArray(n.offsets)&&n.offsets.length?n.offsets:(t.displayRewards||[]).map(t=>({programCode:t.code,description:t.name,displayMonth:t.month,goodsAmount:t.goodsAmount,
quantityText:t.quantityText,offsetAmount:t.offsetAmount}))}function b(t){const n=r(t).summary||{};return{...t.totals||{},...n,totalVatAmount:n.totalVatAmount||t.totals?.tax||0,
amountInWords:n.amountInWords||t.totals?.totalAmountText||""}}function $(t){
const n=r(t).pagination||{},e=v(t),o=y(t),s=m(t),i=n.pagesPerCopy||(o.length||e.length>4||s.length>18?2:1);return{pagesPerCopy:i,copies:n.copies||["Liên 1","Liên 2"],
showPromotionHeaderOnFirstPage:i>1}}function f(t){const n=Number(String(t||0).replace(",","."))||0;return n?n.toLocaleString("vi-VN",{minimumFractionDigits:2,
maximumFractionDigits:2}):""}function T(t){return String(t?.promotionCode||t?.programCode||t?.ctkmCode||t?.code||"").trim()}function A(t){
const n=[t?.promotionType,t?.discountType,t?.level,t?.scope,t?.sourceType,t?.type,t?.promotionLevel,t?.applyScope,t?.mechanismType].filter(Boolean).join(" ").toLowerCase()
;return n.includes("group")||n.includes("invoice")||n.includes("order")||n.includes("bill")||n.includes("basket")||n.includes("cart")||n.includes("nhom")||n.includes("nhóm")||n.includes("hoa_don")||n.includes("hóa đơn")||n.includes("hoá đơn")||n.includes("don_hang")||n.includes("đơn hàng")
}function N(t){return String(t?.description||t?.promotionDescription||t?.programDescription||t?.promotionName||t?.name||t?.title||"").trim()}function C(t){
return Number(t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??t?.purchaseAmountBeforeTax??t?.purchaseAmount??t?.goodsAmountBeforeTax??t?.goodsAmount??t?.amountBeforeTax??0)||0}
function w(t){return Number(t?.discountBeforeTax??t?.beforeTax??t?.ckBeforeTax??t?.discountAmountBeforeTax??t?.promotionBeforeTax??0)||0}function P(t){
return Number(t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax??t?.promotionAfterTax??0)||0}function x(t){const n=new Map;for(const e of t||[]){
const t=T(e);if(!t)continue;n.has(t)||n.set(t,{code:t,description:N(e),qualifiedAmount:0,discountPercent:"",discountBeforeTax:0,discountAfterTax:0,hasGroupDiscount:!1,
_sortIndex:n.size});const o=n.get(t);if(o.description||(o.description=N(e)),o.qualifiedAmount+=C(e),o.discountBeforeTax+=w(e),o.discountAfterTax+=P(e),A(e)){o.hasGroupDiscount=!0
;const t=f(e.discountPercent??e.percent??e.rate??e.discountRate);t&&!o.discountPercent&&(o.discountPercent=t)}}return Array.from(n.values()).sort((t,n)=>t._sortIndex-n._sortIndex)}
function I(t){return`(${String(t||"Liên 1").replace(/[()]/g,"").trim()})`}function G(t,n){return`${t}/ ${n}`}function S(t,n){return o(t,n||0)}function E(){
return'\n    <div class="dms-section-title">CHI TIẾT KHUYẾN MÃI: (B+C)</div>\n    <table class="dms-detail-table dms-promotion-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CTKM Tiền</th>\n          <th>Khuyến mãi bằng tiền</th>\n          <th style="width:25mm">Giá trị hàng hóa mua</th>\n          <th style="width:18mm">% chiết khấu</th>\n          <th style="width:24mm">Tiền CK trước thuế</th>\n          <th style="width:24mm">Tiền CK sau thuế</th>\n        </tr>\n      </thead>\n    </table>'
}function R(t){
return`\n    <table class="print-table">\n      <thead>\n        <tr>\n          <th style="width:8mm">STT</th>\n          <th style="width:24mm">Mã hàng</th>\n          <th>Tên hàng</th>\n          <th class="excel-only-column" style="width:16mm">Quy cách</th>\n          <th style="width:16mm">ĐVT</th>\n          <th style="width:18mm">Thùng/Lẻ</th>\n          <th style="width:18mm">SL lẻ</th>\n          <th class="excel-only-column" style="width:24mm">Giá bán</th>\n          <th style="width:24mm">Đơn giá chứng từ</th>\n          <th style="width:28mm">Thành tiền</th>\n        </tr>\n      </thead>\n      <tbody>${t.items.length?t.items.map(n=>`\n      <tr>\n        <td class="center">${n.stt}</td>\n        <td class="mono">${i(n.code)}</td>\n        <td>${i(n.name)}</td>\n        <td class="right excel-only-column">${s(t,n.catalogPackingQty)}</td>\n        <td class="center">${i(n.unit)}</td>\n        <td class="center">${i(n.caseDisplay)}</td>\n        <td class="right">${o(t,n.qty)}</td>\n        <td class="right excel-only-column">${s(t,n.catalogSalePrice)}</td>\n        <td class="right">${o(t,n.price)}</td>\n        <td class="right">${o(t,n.amount)}</td>\n      </tr>`).join(""):'<tr><td colspan="10" class="center">Chưa có dòng hàng</td></tr>'}</tbody>\n    </table>`
}function M(t){const n=Array.isArray(t.masterKpis)?t.masterKpis:[];if(!n.length)return""
;const e=n.map(n=>`\n    <tr>\n      <td><b>${i(n.code)}</b>${n.note?`<div class="muted">Ghi chú: ${i(n.note)}</div>`:""}</td>\n      <td class="right">${o(t,n.productSaleAmount)}</td>\n      <td class="right">${o(t,n.promotionAmount)}</td>\n      <td class="right">${o(t,n.payableAmount)}</td>\n    </tr>`).join(""),s=t.masterKpiTotals||{}
;return`\n    <div class="section-title">BÁO CÁO KPI ĐƠN TỔNG ĐÃ GỘP</div>\n    <table class="print-table master-kpi-table">\n      <thead>\n        <tr>\n          <th>Mã đơn + ghi chú</th>\n          <th style="width:32mm">Giá trị đơn tổng</th>\n          <th style="width:32mm">Tổng khuyến mại</th>\n          <th style="width:36mm">Tổng tiền phải thu</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${e}\n        <tr class="invoice-total-row">\n          <td class="right">Tổng cộng</td>\n          <td class="right">${o(t,s.productSaleAmount)}</td>\n          <td class="right">${o(t,s.promotionAmount)}</td>\n          <td class="right">${o(t,s.payableAmount)}</td>\n        </tr>\n      </tbody>\n    </table>`
}function H(t,n,e=""){const s=e?` - ${e}`:""
;return`\n    <div class="simple-print-header">\n      <div>\n        <h2>${i(t.company.name)}</h2>\n        <p>${i(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?"Các đơn tổng":"Mã đơn tổng"}</b><span>${i(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">${i(n)}${i(s)}</h1>\n    <div class="info-grid">\n      <div><b>${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?"Gồm đơn tổng":"Mã đơn tổng"}:</b> ${i(t.document.masterOrderCodes&&t.document.masterOrderCodes.length?t.document.masterOrderCodes.join(", "):t.document.code)}</div>\n      <div><b>Ngày giao:</b> ${i(t.document.date)}</div>\n      <div><b>Nhân viên giao hàng:</b> ${i(t.delivery.code)} - ${i(t.delivery.name)}</div>\n      <div><b>Tuyến:</b> ${i(t.delivery.route)}</div>\n      ${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?`<div><b>Số đơn tổng đã chọn:</b> ${o(t,t.document.selectedMasterOrderCount||0)}</div>`:""}\n      <div><b>Số đơn con:</b> ${o(t,t.totals.orderCount)}</div>\n      <div><b>Giá trị đơn tổng:</b> ${o(t,t.totals.totalAmount)} đ</div>\n      ${t.document.note?`<div class="full"><b>Ghi chú:</b> ${i(t.document.note)}</div>`:""}\n    </div>`
}function O(t){return(Number(t.qty||t.quantity||0)||0)*(Number(t.price||t.salePrice||0)||0)}function k(t,n,e=[],r={}){
const a=Boolean(r.isPromo),d=r.priceLabel||"Giá bán",c=r.amountLabel||"Thành tiền",l="giá bán"!==String(d).trim().toLowerCase(),m=l?9:8,h=e.length?e.map((n,e)=>{const r=O(n)
;return`\n        <tr class="${a?"promo-line-row":"sale-line-row"}">\n          <td class="center">${e+1}</td>\n          <td class="mono">${i(n.code)}</td>\n          <td>${i(n.name)}${a?'<div class="muted">Xuất khuyến mại</div>':""}</td>\n          <td class="right excel-only-column">${s(t,n.catalogPackingQty)}</td>\n          <td class="center">${i(n.caseDisplay)}</td>\n          <td class="right">${o(t,n.qty)}</td>\n          ${l?`<td class="right excel-only-column">${s(t,n.catalogSalePrice)}</td>`:""}\n          <td class="right">${o(t,n.price)}</td>\n          <td class="right">${o(t,r)}</td>\n        </tr>`
}).join(""):`<tr><td colspan="${m}" class="center">${a?"Không có hàng khuyến mại":"Không có hàng bán"}</td></tr>`,u=e.reduce((t,n)=>t+Number(n.qty||0),0),p=e.reduce((t,n)=>t+O(n),0)
;return`\n    <div class="master-line-section ${a?"promo-section":"sale-section"}">\n      <div class="section-title">${i(n)}</div>\n      <table class="print-table master-picking-table">\n        <thead>\n          <tr>\n            <th style="width:4%">STT</th>\n            <th style="width:13%">Mã sản phẩm</th>\n            <th style="width:39%">Tên sản phẩm</th>\n            <th class="excel-only-column" style="width:8%">Quy cách</th>\n            <th style="width:10%">Thùng/Lẻ</th>\n            <th style="width:8%">SL lẻ</th>\n            ${l?'<th class="excel-only-column" style="width:11%">Giá bán</th>':""}\n            <th style="width:11%">${i(d)}</th>\n            <th style="width:15%">${i(c)}</th>\n          </tr>\n        </thead>\n        <tbody>\n          ${h}\n          <tr class="invoice-total-row">\n            <td colspan="5" class="right">Tổng ${i(n)}</td>\n            <td class="right">${o(t,u)}</td>\n            ${l?"<td></td>":""}\n            <td></td>\n            <td class="right">${o(t,p)}</td>\n          </tr>\n        </tbody>\n      </table>\n    </div>`
}function K(t){return(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],saleItems:t.items||[],
promoItems:[],totalQty:t.totals.totalQty,totalAmount:t.totals.totalAmount}]).map(n=>{
const e=Array.isArray(n.saleItems)?n.saleItems:(n.items||[]).filter(t=>!t.isPromo&&"PROMO"!==t.lineType),o=Array.isArray(n.promoItems)?n.promoItems:(n.items||[]).filter(t=>t.isPromo||"PROMO"===t.lineType)
;return`\n      <div class="master-warehouse-block">\n        <div class="section-title master-warehouse-title">${i(n.name||n.code)}</div>\n        ${k(t,`${n.name||n.code} - Hàng bán`,e)}\n        ${k(t,`${n.name||n.code} - Xuất khuyến mại`,o,{
isPromo:!0})}\n      </div>`}).join("")}function B(t=["Người lập phiếu","Khách hàng","Thủ kho / Giao hàng"]){
return`\n    <div class="signature-row">\n      ${t.map(t=>`<div><b>${i(t)}</b><span>(Ký, ghi rõ họ tên)</span></div>`).join("")}\n    </div>`}function D(){
return'\n  <div class="print-preview-actions">\n    <button type="button" data-print-action="close">Bỏ qua</button>\n    <button type="button" data-print-action="print">In đơn</button>\n    <button type="button" data-print-action="excel">Xuất Excel</button>\n  </div>\n  <script src="/js/print-preview-actions.js?v=phase09-csp-v1"><\/script>'
}function q(t,n,e,o={}){const s=o.compact?" compact-print":""
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${i(t)} - ${i(n.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body>\n  ${D()}\n  <div class="print-page${s}">\n    ${e}\n    <div class="print-footer">In lúc: ${i(n.meta.printedAt)}</div>\n  </div>\n</body>\n</html>`
}function _(t){const n="MASTER_AGGREGATE_SELECTED"===t.document.printMode,e=n?"ĐƠN TỔNG GỘP":"PHIẾU NHẶT HÀNG ĐƠN TỔNG";if(n){
const n=(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],saleItems:t.items||[],promoItems:[]
}]).map(n=>{const s={qty:(n.items||[]).reduce((t,n)=>t+Number(n.qty||n.quantity||0),0),amount:(n.items||[]).reduce((t,n)=>t+Number(n.amount||0),0)}
;return`\n        <div class="print-page">\n          ${H(t,e,n.name||n.code)}\n          ${M(t)}\n          <div class="master-warehouse-block">\n            <div class="section-title master-warehouse-title">${i(n.name||n.code)}</div>\n            ${k(t,`${n.name||n.code} - Hàng bán`,Array.isArray(n.saleItems)?n.saleItems:[])}\n            ${k(t,`${n.name||n.code} - Xuất khuyến mại`,Array.isArray(n.promoItems)?n.promoItems:[],{
isPromo:!0
})}\n          </div>\n          <div class="total-box">\n            <div><span>Tổng số lượng liên ${i(n.name||n.code)}:</span><b>${o(t,s.qty)}</b></div>\n            <div><span>Giá trị liên ${i(n.name||n.code)}:</span><b>${o(t,s.amount)}</b></div>\n            <div><span>Số đơn con:</span><b>${o(t,t.totals.orderCount)}</b></div>\n          </div>\n          ${B(["Người lập phiếu","Người giao hàng",n.name||n.code])}\n          <div class="print-footer">In lúc: ${i(t.meta.printedAt)}</div>\n        </div>`
}).join("")
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${i(e)} - ${i(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body>\n  ${D()}\n  ${n}\n</body>\n</html>`
}
const s=`\n    ${H(t,e)}\n    ${M(t)}\n    ${K(t)}\n    <div class="total-box">\n      <div><span>Tổng số lượng:</span><b>${o(t,t.totals.totalQty)}</b></div>\n      <div><span>Giá trị đơn tổng:</span><b>${o(t,t.totals.totalAmount)}</b></div>\n      <div><span>Số đơn con:</span><b>${o(t,t.totals.orderCount)}</b></div>\n    </div>\n    ${B(["Người lập phiếu","Người giao hàng","Kho HC","Kho PC"])}`
;return q(e,t,s)}function L(t){const n=String(t.document?.printMode||"").toUpperCase();return n.includes("RETURN")?"RETURN":n.includes("IMPORT")?"IMPORT":"MASTER"}function U(t){
if(t.document?.title)return t.document.title;const n=L(t)
;return"RETURN"===n?"ĐƠN TỔNG TRẢ HÀNG":"IMPORT"===n?"IMPORT_AGGREGATE_SELECTED"===t.document?.printMode?"ĐƠN TỔNG NHẬP KHO":"PHIẾU NHẬP KHO":"MASTER_AGGREGATE_SELECTED"===t.document?.printMode?"ĐƠN TỔNG GỘP":"PHIẾU NHẶT HÀNG ĐƠN TỔNG"
}function V(t,n){
const e=Array.isArray(t.document?.sourceCodes)&&t.document.sourceCodes.length?t.document.sourceCodes:Array.isArray(t.document?.masterOrderCodes)?t.document.masterOrderCodes:[],s="RETURN"===n?"Phiếu trả hàng":"IMPORT"===n?"Phiếu nhập":"Đơn tổng"
;return`\n    <div class="info-grid print-info-compact">\n      <div><b>Ngày chứng từ:</b> ${i(t.document.date)}</div>\n      ${"IMPORT"===n?`<div><b>Nhà cung cấp:</b> ${i(t.customer.name)}</div>`:""}\n      ${"IMPORT"!==n?`<div><b>NV giao hàng:</b> ${i(t.delivery.code)}${t.delivery.name?` - ${i(t.delivery.name)}`:""}</div>`:""}\n      ${t.delivery.route?`<div><b>Tuyến:</b> ${i(t.delivery.route)}</div>`:""}\n      <div><b>Số chứng từ con:</b> ${o(t,t.totals.orderCount)}</div>\n      ${e.length?`<div class="full"><b>${s}:</b> ${i(e.join(", "))}</div>`:""}\n      ${t.document.note?`<div class="full"><b>Ghi chú:</b> ${i(t.document.note)}</div>`:""}\n    </div>`
}function j(t){const n=L(t),e=U(t),s=(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],
saleItems:t.items||[],promoItems:[],importItems:[],returnItems:[]}]).map((s,r)=>{
const a=Array.isArray(s.saleItems)?s.saleItems:[],d=Array.isArray(s.promoItems)?s.promoItems:[],c=Array.isArray(s.importItems)&&s.importItems.length?s.importItems:"IMPORT"===n&&s.items||[],l=Array.isArray(s.returnItems)&&s.returnItems.length?s.returnItems:"RETURN"===n&&s.items||[],m="IMPORT"===n?c:"RETURN"===n?l:[...a,...d],h=m.reduce((t,n)=>t+Number(n.qty||n.quantity||0),0),u=m.reduce((t,n)=>t+O(n),0),p="IMPORT"===n?["Người lập phiếu","Người giao hàng","Thủ kho"]:"RETURN"===n?["Người lập phiếu","Nhân viên giao hàng","Thủ kho"]:["Người lập phiếu","Người giao hàng",s.name||s.code],g="IMPORT"===n?k(t,`${s.name||s.code} - Hàng nhập kho`,c,{
priceLabel:"Giá nhập"}):"RETURN"===n?k(t,`${s.name||s.code} - Hàng trả nhập kho`,l,{priceLabel:"Giá trả"}):`${k(t,`${s.name||s.code} - Hàng bán`,a,{priceLabel:"Giá bán"
})}${k(t,`${s.name||s.code} - Xuất khuyến mại`,d,{isPromo:!0,priceLabel:"Giá tham chiếu"})}`
;return`\n      <section class="print-page warehouse-picking-page${r>0?" page-break-before":""}">\n        <div class="simple-print-header">\n          <div><h2>${i(t.company.name)}</h2><p>${i(t.company.address)}</p></div>\n          <div class="print-code"><b>Mã chứng từ</b><span>${i(t.document.code)}</span></div>\n        </div>\n        <h1 class="print-title">${i(e)} - ${i(s.name||s.code)}</h1>\n        ${V(t,n)}\n        ${0===r?M(t):""}\n        ${g}\n        <div class="total-box print-total-compact">\n          <div><span>Tổng số lượng:</span><b>${o(t,h)}</b></div>\n          <div><span>Tổng giá trị:</span><b>${o(t,u)}</b></div>\n          <div><span>Số chứng từ con:</span><b>${o(t,t.totals.orderCount)}</b></div>\n        </div>\n        ${B(p)}\n        <div class="print-footer">In lúc: ${i(t.meta.printedAt)}</div>\n      </section>`
}).join("")
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${i(e)} - ${i(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body class="warehouse-picking-body">\n  ${D()}\n  ${s}\n</body>\n</html>`
}function Q(t){
return q("PHIẾU NHẬP KHO",t,`\n    <div class="simple-print-header">\n      <div>\n        <h2>${i(t.company.name)}</h2>\n        <p>${i(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>Mã phiếu</b><span>${i(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">PHIẾU NHẬP KHO</h1>\n    <div class="info-grid">\n      <div><b>Ngày nhập:</b> ${i(t.document.date)}</div>\n      <div><b>Nhà cung cấp:</b> ${i(t.customer.name)}</div>\n      <div class="full"><b>Ghi chú:</b> ${i(t.document.note)}</div>\n    </div>\n    ${R(t)}\n    <div class="total-box">\n      <div><span>Tổng số lượng nhập:</span><b>${o(t,t.totals.totalQty)}</b></div>\n      <div><span>Tổng giá trị:</span><b>${o(t,t.totals.totalAmount)}</b></div>\n    </div>\n    ${B(["Người lập phiếu","Người giao hàng","Thủ kho"])}`)
}function F(t){
return q("PHIẾU THU TIỀN",t,`\n    <div class="simple-print-header">\n      <div>\n        <h2>${i(t.company.name)}</h2>\n        <p>${i(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>Mã phiếu</b><span>${i(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">PHIẾU THU TIỀN</h1>\n    <div class="info-grid">\n      <div><b>Ngày thu:</b> ${i(t.document.date)}</div>\n      <div><b>Người thu:</b> ${i(t.staff.name)}</div>\n      <div><b>Mã KH:</b> ${i(t.customer.code)}</div>\n      <div><b>Khách hàng:</b> ${i(t.customer.name)}</div>\n      <div class="full"><b>Địa chỉ:</b> ${i(t.customer.address)}</div>\n    </div>\n    <div class="receipt-money"><span>Số tiền thu:</span><b>${o(t,t.totals.paid||t.totals.totalAmount)} đ</b></div>\n    <p class="note"><b>Nội dung:</b> ${i(t.document.note||"Thu tiền bán hàng")}</p>\n    ${B(["Người lập phiếu","Người nộp tiền","Thủ quỹ"])}`)
}function Y(t,n=null,e={}){const s=Array.isArray(n)?n:m(t),r=b(t),a=!1!==e.showTotal
;return`\n    <table class="dms-invoice-table">\n      <thead>\n        <tr>\n          <th style="width:4%">STT</th>\n          <th style="width:9%">Mã hàng</th>\n          <th style="width:27%">Tên sản phẩm</th>\n          <th class="excel-only-column" style="width:6%">Quy cách</th>\n          <th style="width:7%">Số lượng<br/>(CS/SU)</th>\n          <th style="width:6%">Số<br/>lượng<br/>(lẻ)</th>\n          <th style="width:9%">Đơn Giá<br/>(Trước Thuế/KM)</th>\n          <th style="width:9%">Giá bán<br/>(Sau Thuế,<br/>Trước KM)</th>\n          <th style="width:9%">Đơn giá<br/>(Sau Thuế/<br/>KM&CK)</th>\n          <th style="width:7%">Thuế<br/>GTGT</th>\n          <th style="width:9%">Thành tiền<br/>(Sau Thuế/<br/>KM&CK)</th>\n        </tr>\n        <tr class="dms-formula-row">\n          <th>A</th><th></th><th></th><th class="excel-only-column">QC</th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7=(5*2)</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${s.length?s.map(n=>`\n      <tr>\n        <td class="center">${i(n.lineNo)}</td>\n        <td class="mono">${i(n.productCode)}</td>\n        <td class="dms-product-name">${i(n.productName)}</td>\n        <td class="right excel-only-column">${o(t,n.conversionRate)}</td>\n        <td class="center">${i(n.quantityCsSu)}</td>\n        <td class="right">${o(t,n.quantity)}</td>\n        <td class="right">${o(t,n.priceBeforeTaxBeforePromotion)}</td>\n        <td class="right">${o(t,n.priceAfterTaxBeforePromotion)}</td>\n        <td class="right">${o(t,n.priceAfterTaxAfterPromotion)}</td>\n        <td class="right">${o(t,n.vatAmount)}</td>\n        <td class="right">${o(t,n.lineAmount)}</td>\n      </tr>`).join(""):'<tr><td colspan="11" class="center">Chưa có dòng hàng</td></tr>'}\n        ${a?`<tr class="dms-total-row">\n          <td colspan="5" class="center">Tổng cộng (A)</td>\n          <td class="right">${S(t,r.totalQty)}</td>\n          <td></td><td></td><td></td>\n          <td></td>\n          <td class="right">${S(t,r.goodsAmountAfterPromotion)}</td>\n        </tr>`:""}\n      </tbody>\n    </table>`
}function X(t){
const n=x(v(t)),e=b(t),o=n.length?n.map(n=>`\n      <tr>\n        <td class="mono">${i(n.code)}</td>\n        <td>${i(n.description)}</td>\n        <td class="right">${S(t,n.qualifiedAmount)}</td>\n        <td class="right">${n.hasGroupDiscount?i(n.discountPercent):""}</td>\n        <td class="right">${S(t,n.discountBeforeTax)}</td>\n        <td class="right">${S(t,n.discountAfterTax)}</td>\n      </tr>`).join(""):'<tr class="dms-empty-row"><td colspan="6">&nbsp;</td></tr>',s=n.length?n.reduce((t,n)=>t+Number(n.discountAfterTax||0),0):Number(e.totalPromotionAmount??e.promotionAmount??t.totals?.promotionValue??0)||0
;return`\n    <div class="dms-section-title">CHI TIẾT KHUYẾN MÃI: (B+C)</div>\n    <table class="dms-detail-table dms-promotion-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CTKM Tiền</th>\n          <th>Khuyến mãi bằng tiền</th>\n          <th style="width:25mm">Giá trị hàng hóa mua</th>\n          <th style="width:18mm">% chiết khấu</th>\n          <th style="width:24mm">Tiền CK trước thuế</th>\n          <th style="width:24mm">Tiền CK sau thuế</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${o}\n        <tr class="dms-total-row"><td colspan="5" class="right">Tổng giá trị khuyến mãi tiền (C)</td><td class="right">${S(t,s)}</td></tr>\n      </tbody>\n    </table>`
}function W(t){const n=y(t),e=b(t),o=Number(e.totalOffsetAmount??e.displayRewardOffset??t.totals?.displayRewardTotal??0)||0
;return n.length||o?`\n    <div class="dms-section-title">CHI TIẾT CẤN TRỪ NỢ:(D+E)</div>\n    <table class="dms-detail-table dms-reward-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CT Trưng bày</th>\n          <th>Nội dung Chương trình trưng bày</th>\n          <th style="width:20mm">Tháng trưng bày</th>\n          <th style="width:24mm">Chi trả trưng bày (hàng hóa)</th>\n          <th style="width:20mm">Số lượng (Thùng/lẻ)</th>\n          <th style="width:25mm">Chi trả trưng bày (cấn trừ nợ)</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${n.length?n.map(n=>`\n      <tr>\n        <td class="mono">${i(n.programCode)}</td>\n        <td>${i(n.description)}</td>\n        <td class="center">${i(n.displayMonth||n.month)}</td>\n        <td class="right">${n.goodsAmount?S(t,n.goodsAmount):""}</td>\n        <td class="center">${i(n.quantityText)}</td>\n        <td class="right">${S(t,n.offsetAmount)}</td>\n      </tr>`).join(""):'<tr class="dms-empty-row"><td colspan="6">&nbsp;</td></tr>'}\n        <tr class="dms-total-row"><td colspan="5" class="right">Tổng giá trị nhận được từ CT trưng bày (D)</td><td class="right">${S(t,o)}</td></tr>\n      </tbody>\n    </table>`:""
}function z(t,n,e,o){
const s=a(t),r=d(t),m=c(t),h=l(t),u=I(n),p=G(e,o),g=`${i(h.staffCode)}${h.staffName?` - ${i(h.staffName)}`:""}${h.phone?` - ${i(h.phone)}`:""}`,v=`${i(m.customerCode)}${m.customerName?` - ${i(m.customerName)}`:""}${m.phone?` - ${i(m.phone)}`:""}`,y=`${i(r.code)}${r.name?` - ${i(r.name)}`:""}`
;return`\n    <div class="dms-header-lines dms-invoice-header-left dms-invoice-header-right">\n      <div class="dms-title-header">\n        <div></div>\n        <div class="dms-title-line">PHIẾU GIAO NHẬN VÀ THANH TOÁN</div>\n        <div class="dms-truck-cell"><span>Số xe tải:</span> ${i(s.truckNo)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Số hóa đơn:</span> ${i(s.invoiceCode)}</div>\n        <div class="dms-line-right dms-line-right-split">\n          <span><span>Loại hóa đơn:</span> ${i(s.invoiceType)}</span>\n          <span class="dms-copy-page-cell"><span>${i(u)}</span><span>Trang: ${p}</span></span>\n        </div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Số đơn hàng:</span> ${i(s.orderCode)}</div>\n        <div class="dms-line-right"><span>Thời gian đặt hàng:</span> ${i(s.orderDateTime)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>NVBH:</span> ${g}</div>\n        <div class="dms-line-right"><span>Nhà phân phối:</span> ${y}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Khách hàng - Điện thoại:</span> ${v}</div>\n        <div class="dms-line-right"><span>Địa chỉ:</span> ${i(r.address)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Địa chỉ giao hàng:</span> ${i(m.deliveryAddress)}</div>\n        <div class="dms-line-right"><span>Điện thoại:</span> ${i(r.phone)}</div>\n      </div>\n\n      <div class="dms-header-line dms-single-line">\n        <div class="dms-line-left"><span>Điều khoản thanh toán:</span> ${i(s.paymentTerm)}</div>\n      </div>\n\n      <div class="dms-header-line dms-single-line">\n        <div class="dms-line-left"><span>MST:</span> ${i(s.taxCode||m.taxCode)}</div>\n      </div>\n    </div>`
}function J(t=[],n=24){const e=Math.max(1,Number(n||24)),o=[];for(let n=0;n<t.length;n+=e)o.push(t.slice(n,n+e));return o.length?o:[[]]}function Z(t){
return v(t).length>0||y(t).length>0}function tt(t){const n=$(t),e=b(t)
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>Phiếu giao nhận DMS - ${i(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body class="dms-print-body">\n  ${D()}\n  ${n.copies.map(o=>{
const s=m(t),r=J(s,Number(n.itemPageSize||24)),a=Z(t)&&(s.length>18||n.detailRows>4||n.pagesPerCopy>r.length),d=r.length+(a?1:0);return r.map((n,s)=>{const c=s===r.length-1
;return`\n        <section class="print-page dms-print-page">\n          ${z(t,o,s+1,d)}\n          ${Y(t,n,{showTotal:c
})}\n          ${c?`\n      <table class="dms-summary-split-table">\n        <tbody>\n          <tr class="dms-payable-row">\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Số tiền phải thanh toán (A7-D-E-H)</td>\n            <td class="dms-summary-value-cell">${S(t,e.payableAmount??t.totals?.payable??t.totals?.totalAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tổng tiền sau thuế chưa trừ KM (G) = (2)*(4):</td>\n            <td class="dms-summary-value-cell">${S(t,e.grossAmountBeforePromotion??t.totals?.goodsAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell dms-amount-words-cell"><b>Số tiền viết bằng chữ :</b> <span class="dms-amount-words-text">${i(e.amountInWords||t.totals.totalAmountText)}</span></td>\n            <td class="dms-summary-label-cell">Tổng trị giá khuyến mãi bằng hàng và tiền (B+C):</td>\n            <td class="dms-summary-value-cell">${S(t,e.totalPromotionAmount??t.totals?.promotionValue)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Cấn trừ tiền (D+E+H):</td>\n            <td class="dms-summary-value-cell">${S(t,e.totalOffsetAmount??t.totals?.displayRewardTotal)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tổng tiền CK của NPP (F)=(G-C)* 0,00% :</td>\n            <td class="dms-summary-value-cell">${S(t,e.nppDiscountAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tỉ lệ KM & CK của đơn hàng [(B+C+F)/G]*100%:</td>\n            <td class="dms-summary-value-cell">${f(e.promotionRate??t.totals?.promotionRate)}%</td>\n          </tr>\n        </tbody>\n      </table>\n      <div class="dms-signature">\n        <div><b>Người lập biểu</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Người bán hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Nhân viên giao hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Người nhận hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n      </div>`:""}\n          ${c&&!a?X(t)+W(t):""}\n          ${c&&a?E():""}\n        </section>`
}).join("")+(a?`\n      <section class="print-page dms-print-page">\n        ${z(t,o,r.length+1,d)}\n        ${X(t)}\n        ${W(t)}\n      </section>`:"")
}).join("")}\n</body>\n</html>`}module.exports={ORDER_SINGLE:t,DMS_DELIVERY_INVOICE:t,SALES_INVOICE:t,SALES_INVOICE_DMS_EXACT_V1:t,ORDER_TOTAL:j,WAREHOUSE_PICKING:j,IMPORT_ORDER:j,
PAYMENT_RECEIPT:F};
