const flexModel = require('./_flexModel');

module.exports = flexModel('ArLedger', 'arLedgers', {
  id: String,
  tenantId: String,
  code: String,
  type: String,
  date: String,
  account: String,
  customerId: String,
  customerCode: String,
  customerName: String,
  salesmanCode: String,
  salesmanName: String,
  salesStaffCode: String,
  salesStaffName: String,
  deliveryStaffCode: String,
  deliveryStaffName: String,
  orderId: String,
  orderCode: String,
  salesOrderId: String,
  salesOrderCode: String,
  refId: String,
  refCode: String,
  refType: String,
  amount: Number,
  debit: Number,
  credit: Number,
  note: String,
  status: String,
  source: String,
  sourceType: String,
  sourceId: String,
  sourceCode: String,
  sourceOrderId: String,
  sourceOrderCode: String,
  referenceId: String,
  referenceCode: String,
  orderType: String,
  collectorType: String,
  collectorCode: String,
  collectorName: String,
  accountingConfirmedBy: String,

  // A4 - Cash in transit metadata
  method: String,
  paymentMethod: String,
  deliveryDate: String,
  masterOrderId: String,
  masterOrderCode: String,

  accountingConfirmed: Boolean,
  accountingStatus: String,
  createdAt: String,
  updatedAt: String
});
